### ISSUE TITLE
Feature suggestion: automated db backup

### ISSUE THREAD

**Issue by marekyggdrasil** [aosingh/sqlite_rx#6]
I think it would be really useful to be able to make db backups without killing the server process. It would be nice if backup could be scheduled using something like https://github.com/dbader/schedule and performed without breaking connections from the clients. My idea is, if client runs a query while backup is performed server would still notify the client of this so that the client could properly handle such exception.

I have a Python script that backs up the sqlite DB, if you find this idea appealing how about we join forces @aosingh ? If not, maybe you could give some hints what is the best way to manage backups under `sqlite_rx` setup.

Thanks in advance!

**Comment by aosingh** [comment]
Thank you for your feature suggestion @marekyggdrasil 

- I will check the behavior when requests are sent to the server while a backup is in progress. 

- Should `sqlite_rx` support backups or backups can be independently run using a utility script without the clients being aware? 

- Starting with Python 3.7, a [backup()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.backup) method is introduced. This method makes a backup of an SQLite database even while it’s being accessed by other clients, or concurrently by the same connection.

- If we decide to use the `backup()` method, then it will not be backward compatible with Python 3.6

I am still thinking a bit more.

**Comment by marekyggdrasil** [comment]
Thank you for the feedback, please take your time with decision how to proceed. I am not an expert on sqlite but I did see I could not perform backup (using a utility script) while `sqlite_rx` is serving it. I do not know why, I suspect it creates some sort of lock to deal with concurrency.

**Comment by aosingh** [comment]
hi @marekyggdrasil 

I am currently working on the latest release of [sqlite_rx](https://github.com/aosingh/sqlite_rx/tree/v1.0.2) which includes the backup procedure.

## Approach

The backup procedure can be scheduled to run as a background thread during server startup. Also, due to the limitations of the multiprocessing module,  backup is not supported on Windows OS. 

```
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: can't pickle _thread.lock objects
```

Link to the documentation: https://github.com/aosingh/sqlite_rx/tree/v1.0.2#backup

Currently, I am working on documentation and will release the latest version soon.

**Comment by marekyggdrasil** [comment]
You are awesome @aosingh !
